using System;
using System.Collections.Generic;

#nullable disable

namespace ODataDemo.Models
{
    public partial class Event
    {
        public string Etag { get; set; }
        public long Id { get; set; }
        public int? AccruedInterestDays { get; set; }
        public string ActualContractualCode { get; set; }
        public bool? AdditionalTaxIsSet { get; set; }
        public string AdditionalTaxPrimaryCurrencyCode { get; set; }
        public decimal? AdditionalTaxPrimaryValue { get; set; }
        public string AdditionalTaxSecondaryCurrencyCode { get; set; }
        public decimal? AdditionalTaxSecondaryValue { get; set; }
        public string AdditionalTaxType { get; set; }
        public bool? Affidavit { get; set; }
        public string Aftcode { get; set; }
        public string AftmanualSetCode { get; set; }
        public bool? AnnouncementDateIsSet { get; set; }
        public DateTime? AnnouncementDateValue { get; set; }
        public string AnnouncementDateType { get; set; }
        public string AnnouncementDateUtcOffset { get; set; }
        public string BbgDividendTypeCode { get; set; }
        public bool? BidIntervalRateIsSet { get; set; }
        public string BidIntervalRatePrimaryCurrencyCode { get; set; }
        public decimal? BidIntervalRatePrimaryValue { get; set; }
        public string BidIntervalRateSecondaryCurrencyCode { get; set; }
        public decimal? BidIntervalRateSecondaryValue { get; set; }
        public string BidIntervalRateType { get; set; }
        public bool? BlockingPeriodIsSet { get; set; }
        public DateTime? BlockingPeriodStartDate { get; set; }
        public DateTime? BlockingPeriodEndDate { get; set; }
        public string BlockingPeriodType { get; set; }
        public bool? BookClosureperiodIsSet { get; set; }
        public DateTime? BookClosureperiodStartDate { get; set; }
        public DateTime? BookClosureperiodEndDate { get; set; }
        public string BookClosureperiodType { get; set; }
        public string CashflowSetId { get; set; }
        public string CashflowSetTypeCode { get; set; }
        public string ChangeTypeCode { get; set; }
        public string CodeEventisCode { get; set; }
        public string CorporateActionEventStageCode { get; set; }
        public string CouponNumber { get; set; }
        public string DefaultTaxRate { get; set; }
        public string DenominationCode { get; set; }
        public string DepartmentCode { get; set; }
        public bool? DepositorysuspensionperiodforwithdrawalatagentIsSet { get; set; }
        public DateTime? DepositorysuspensionperiodforwithdrawalatagentStartDate { get; set; }
        public DateTime? DepositorysuspensionperiodforwithdrawalatagentEndDate { get; set; }
        public string DepositorysuspensionperiodforwithdrawalatagentType { get; set; }
        public bool? DerivedEffectiveDateIsSet { get; set; }
        public DateTime? DerivedEffectiveDateValue { get; set; }
        public string DerivedEffectiveDateType { get; set; }
        public string DerivedEffectiveDateUtcOffset { get; set; }
        public bool? DerivedExDateIsSet { get; set; }
        public DateTime? DerivedExDateValue { get; set; }
        public string DerivedExDateType { get; set; }
        public string DerivedExDateUtcOffset { get; set; }
        public string DistributionTypeCode { get; set; }
        public string DividendFrequencyCode { get; set; }
        public bool? DueDateIsSet { get; set; }
        public DateTime? DueDateValue { get; set; }
        public string DueDateType { get; set; }
        public string DueDateUtcOffset { get; set; }
        public bool? EffectiveDateIsSet { get; set; }
        public DateTime? EffectiveDateValue { get; set; }
        public string EffectiveDateType { get; set; }
        public string EffectiveDateUtcOffset { get; set; }
        public bool? EntitlementPeriodIsSet { get; set; }
        public DateTime? EntitlementPeriodStartDate { get; set; }
        public DateTime? EntitlementPeriodEndDate { get; set; }
        public string EntitlementPeriodType { get; set; }
        public bool? EusdInterestProportionChIsSet { get; set; }
        public string EusdInterestProportionChPrimaryCurrencyCode { get; set; }
        public decimal? EusdInterestProportionChPrimaryValue { get; set; }
        public string EusdInterestProportionChSecondaryCurrencyCode { get; set; }
        public decimal? EusdInterestProportionChSecondaryValue { get; set; }
        public string EusdInterestProportionChType { get; set; }
        public bool? EusdInterestProportionEuIsSet { get; set; }
        public string EusdInterestProportionEuPrimaryCurrencyCode { get; set; }
        public decimal? EusdInterestProportionEuPrimaryValue { get; set; }
        public string EusdInterestProportionEuSecondaryCurrencyCode { get; set; }
        public decimal? EusdInterestProportionEuSecondaryValue { get; set; }
        public string EusdInterestProportionEuType { get; set; }
        public DateTime? EventDeadline { get; set; }
        public string EventTypeCode { get; set; }
        public bool? ExDateIsSet { get; set; }
        public DateTime? ExDateValue { get; set; }
        public string ExDateType { get; set; }
        public string ExDateUtcOffset { get; set; }
        public int? ExemptionCode { get; set; }
        public bool? ExpiryDateIsSet { get; set; }
        public DateTime? ExpiryDateValue { get; set; }
        public string ExpiryDateType { get; set; }
        public string ExpiryDateUtcOffset { get; set; }
        public string ExtendedNarrativeSerialized { get; set; }
        public string FamilyCode { get; set; }
        public bool? FeesIsSet { get; set; }
        public string FeesPrimaryCurrencyCode { get; set; }
        public decimal? FeesPrimaryValue { get; set; }
        public string FeesSecondaryCurrencyCode { get; set; }
        public decimal? FeesSecondaryValue { get; set; }
        public string FeesType { get; set; }
        public bool? FilingDateIsSet { get; set; }
        public DateTime? FilingDateValue { get; set; }
        public string FilingDateType { get; set; }
        public string FilingDateUtcOffset { get; set; }
        public bool? FiscalStampIsSet { get; set; }
        public string FiscalStampPrimaryCurrencyCode { get; set; }
        public decimal? FiscalStampPrimaryValue { get; set; }
        public string FiscalStampSecondaryCurrencyCode { get; set; }
        public decimal? FiscalStampSecondaryValue { get; set; }
        public string FiscalStampType { get; set; }
        public bool? FixingDateIsSet { get; set; }
        public DateTime? FixingDateValue { get; set; }
        public string FixingDateType { get; set; }
        public string FixingDateUtcOffset { get; set; }
        public bool? FloatingRateFixingDateIsSet { get; set; }
        public DateTime? FloatingRateFixingDateValue { get; set; }
        public string FloatingRateFixingDateType { get; set; }
        public string FloatingRateFixingDateUtcOffset { get; set; }
        public bool? Forexo { get; set; }
        public bool? FrenchTaxRateIsSet { get; set; }
        public string FrenchTaxRatePrimaryCurrencyCode { get; set; }
        public decimal? FrenchTaxRatePrimaryValue { get; set; }
        public string FrenchTaxRateSecondaryCurrencyCode { get; set; }
        public decimal? FrenchTaxRateSecondaryValue { get; set; }
        public string FrenchTaxRateType { get; set; }
        public string Guid { get; set; }
        public bool? HasNoConflicts { get; set; }
        public int? IncomeCode { get; set; }
        public string IncomeTypeCode { get; set; }
        public string InformationStatusCode { get; set; }
        public string InformationStatusTypeCode { get; set; }
        public long? InstrumentIdentityId { get; set; }
        public decimal? InterestAmount { get; set; }
        public string InterestCalculationMethodCode { get; set; }
        public decimal? InterestDaysPerAnnum { get; set; }
        public bool? InterestFractionIsSet { get; set; }
        public string InterestFractionPrimaryCurrencyCode { get; set; }
        public decimal? InterestFractionPrimaryValue { get; set; }
        public string InterestFractionSecondaryCurrencyCode { get; set; }
        public decimal? InterestFractionSecondaryValue { get; set; }
        public string InterestFractionType { get; set; }
        public bool? InterestPeriodIsSet { get; set; }
        public DateTime? InterestPeriodStartDate { get; set; }
        public DateTime? InterestPeriodEndDate { get; set; }
        public string InterestPeriodType { get; set; }
        public bool? InterestRateIsSet { get; set; }
        public string InterestRatePrimaryCurrencyCode { get; set; }
        public decimal? InterestRatePrimaryValue { get; set; }
        public string InterestRateSecondaryCurrencyCode { get; set; }
        public decimal? InterestRateSecondaryValue { get; set; }
        public string InterestRateType { get; set; }
        public long? IntermediateInstrumentIdentityId { get; set; }
        public string IntermediateSecuritiesDispositionOfFractionCode { get; set; }
        public string IntermediateSecuritiesDistributionTypeCode { get; set; }
        public bool? IntermediateSecuritiesExpiryDateIsSet { get; set; }
        public DateTime? IntermediateSecuritiesExpiryDateValue { get; set; }
        public string IntermediateSecuritiesExpiryDateType { get; set; }
        public string IntermediateSecuritiesExpiryDateUtcOffset { get; set; }
        public string IntermediateSecuritiesRenounceableIndicatorCode { get; set; }
        public bool? IntermediateSecuritiesToUnderlyingRatioIsSet { get; set; }
        public string IntermediateSecuritiesToUnderlyingRatioPrimaryCurrencyCode { get; set; }
        public decimal? IntermediateSecuritiesToUnderlyingRatioPrimaryValue { get; set; }
        public string IntermediateSecuritiesToUnderlyingRatioSecondaryCurrencyCode { get; set; }
        public decimal? IntermediateSecuritiesToUnderlyingRatioSecondaryValue { get; set; }
        public string IntermediateSecuritiesToUnderlyingRatioType { get; set; }
        public bool? IntermediateSecuritiesTradingPeriodIsSet { get; set; }
        public DateTime? IntermediateSecuritiesTradingPeriodStartDate { get; set; }
        public DateTime? IntermediateSecuritiesTradingPeriodEndDate { get; set; }
        public string IntermediateSecuritiesTradingPeriodType { get; set; }
        public bool? IsComplete { get; set; }
        public bool? IsConfirmed { get; set; }
        public bool? IsNarrativeChecked { get; set; }
        public string IEventId { get; set; }
        public long? IId { get; set; }
        public string JsonAdditionalTax { get; set; }
        public string JsonBidIntervalRate { get; set; }
        public string JsonBookClosureperiod { get; set; }
        public string JsonDepositorysuspensionperiodforwithdrawalatagent { get; set; }
        public string JsonEusdInterestProportionCh { get; set; }
        public string JsonEusdInterestProportionEu { get; set; }
        public string JsonFees { get; set; }
        public string JsonFilingDate { get; set; }
        public string JsonFiscalStamp { get; set; }
        public string JsonFrenchTaxRate { get; set; }
        public string JsonInterestFraction { get; set; }
        public string JsonInterestRate { get; set; }
        public string JsonIntermediateSecuritiesToUnderlyingRatio { get; set; }
        public string JsonLotteryDateTime { get; set; }
        public string JsonMarketclaimtrackingenddate { get; set; }
        public string JsonMaximumPrice { get; set; }
        public string JsonMaximumquantityofsecurities { get; set; }
        public string JsonMinimumPrice { get; set; }
        public string JsonMinimumQuantitysought { get; set; }
        public string JsonNewPoolFactor { get; set; }
        public string JsonNraamount { get; set; }
        public string JsonNrarate { get; set; }
        public string JsonOfficialAnnouncementPublicationDateTime { get; set; }
        public string JsonOldPoolFactor { get; set; }
        public string JsonPercentageSought { get; set; }
        public string JsonPremiumFraction { get; set; }
        public string JsonRefundOfNra { get; set; }
        public string JsonResultPublicationDateTime { get; set; }
        public string JsonTaxCreditRate { get; set; }
        public string JsonTaxOnIncome { get; set; }
        public string JsonTaxOnProfits { get; set; }
        public string JsonTaxRate { get; set; }
        public string JsonTaxRelatedRate { get; set; }
        public string JsonTidch { get; set; }
        public string JsonTideu { get; set; }
        public string JsonWithholdingTaxRate { get; set; }
        public DateTime? LastChangeDate { get; set; }
        public bool? LastDistributionDateIsSet { get; set; }
        public DateTime? LastDistributionDateValue { get; set; }
        public string LastDistributionDateType { get; set; }
        public string LastDistributionDateUtcOffset { get; set; }
        public int? LastIgnoredRelevantHashcode { get; set; }
        public bool? LotteryDateTimeIsSet { get; set; }
        public DateTime? LotteryDateTimeValue { get; set; }
        public string LotteryDateTimeType { get; set; }
        public string LotteryDateTimeUtcOffset { get; set; }
        public string MandatoryVoluntaryIndicatorCode { get; set; }
        public bool? MarketclaimtrackingenddateIsSet { get; set; }
        public DateTime? MarketclaimtrackingenddateValue { get; set; }
        public string MarketclaimtrackingenddateType { get; set; }
        public string MarketclaimtrackingenddateUtcOffset { get; set; }
        public bool? MaximumPriceIsSet { get; set; }
        public string MaximumPriceCurrencyCode { get; set; }
        public decimal? MaximumPriceValue { get; set; }
        public string MaximumPriceType { get; set; }
        public string MaximumPriceCode { get; set; }
        public decimal? MaximumPriceQuantity { get; set; }
        public string MaximumPriceQuantityTypeCode { get; set; }
        public bool? MaximumPriceIsCalculated { get; set; }
        public decimal? MaximumPriceValue2 { get; set; }
        public string MaximumPriceCurrency2Code { get; set; }
        public bool? MaximumquantityofsecuritiesIsSet { get; set; }
        public decimal? MaximumquantityofsecuritiesValue { get; set; }
        public string MaximumquantityofsecuritiesType { get; set; }
        public bool? MeetingDateIsSet { get; set; }
        public DateTime? MeetingDateValue { get; set; }
        public string MeetingDateType { get; set; }
        public string MeetingDateUtcOffset { get; set; }
        public bool? MinimumPriceIsSet { get; set; }
        public string MinimumPriceCurrencyCode { get; set; }
        public decimal? MinimumPriceValue { get; set; }
        public string MinimumPriceType { get; set; }
        public string MinimumPriceCode { get; set; }
        public decimal? MinimumPriceQuantity { get; set; }
        public string MinimumPriceQuantityTypeCode { get; set; }
        public bool? MinimumPriceIsCalculated { get; set; }
        public decimal? MinimumPriceValue2 { get; set; }
        public string MinimumPriceCurrency2Code { get; set; }
        public string MinimumProcessingLevel { get; set; }
        public bool? MinimumQuantitysoughtIsSet { get; set; }
        public decimal? MinimumQuantitysoughtValue { get; set; }
        public string MinimumQuantitysoughtType { get; set; }
        public string NarrativeSerialized { get; set; }
        public string NewName { get; set; }
        public bool? NewPoolFactorIsSet { get; set; }
        public string NewPoolFactorPrimaryCurrencyCode { get; set; }
        public decimal? NewPoolFactorPrimaryValue { get; set; }
        public string NewPoolFactorSecondaryCurrencyCode { get; set; }
        public decimal? NewPoolFactorSecondaryValue { get; set; }
        public string NewPoolFactorType { get; set; }
        public bool? NraamountIsSet { get; set; }
        public string NraamountCurrencyCode { get; set; }
        public decimal? NraamountValue { get; set; }
        public string NraamountType { get; set; }
        public string NraamountCode { get; set; }
        public decimal? NraamountQuantity { get; set; }
        public string NraamountQuantityTypeCode { get; set; }
        public bool? NraamountIsCalculated { get; set; }
        public decimal? NraamountValue2 { get; set; }
        public string NraamountCurrency2Code { get; set; }
        public bool? NrarateIsSet { get; set; }
        public string NrarateCurrencyCode { get; set; }
        public decimal? NrarateValue { get; set; }
        public string NrarateType { get; set; }
        public string NrarateCode { get; set; }
        public decimal? NrarateQuantity { get; set; }
        public string NrarateQuantityTypeCode { get; set; }
        public bool? NrarateIsCalculated { get; set; }
        public decimal? NrarateValue2 { get; set; }
        public string NrarateCurrency2Code { get; set; }
        public string Offeror { get; set; }
        public string OfferTypeCode { get; set; }
        public bool? OfficialAnnouncementPublicationDateTimeIsSet { get; set; }
        public DateTime? OfficialAnnouncementPublicationDateTimeValue { get; set; }
        public string OfficialAnnouncementPublicationDateTimeType { get; set; }
        public string OfficialAnnouncementPublicationDateTimeUtcOffset { get; set; }
        public string OfficialEventReference { get; set; }
        public bool? OldPoolFactorIsSet { get; set; }
        public string OldPoolFactorPrimaryCurrencyCode { get; set; }
        public decimal? OldPoolFactorPrimaryValue { get; set; }
        public string OldPoolFactorSecondaryCurrencyCode { get; set; }
        public decimal? OldPoolFactorSecondaryValue { get; set; }
        public string OldPoolFactorType { get; set; }
        public int? OptionCount { get; set; }
        public string OrderTypeCode { get; set; }
        public string OwnerCode { get; set; }
        public string ParentEvent { get; set; }
        public int? ParentIncomeCode { get; set; }
        public string PartialTypeOfDividendCode { get; set; }
        public bool? PaymentDateIsSet { get; set; }
        public DateTime? PaymentDateValue { get; set; }
        public string PaymentDateType { get; set; }
        public string PaymentDateUtcOffset { get; set; }
        public string PaymentFunctionCode { get; set; }
        public bool? PercentageSoughtIsSet { get; set; }
        public string PercentageSoughtPrimaryCurrencyCode { get; set; }
        public decimal? PercentageSoughtPrimaryValue { get; set; }
        public string PercentageSoughtSecondaryCurrencyCode { get; set; }
        public decimal? PercentageSoughtSecondaryValue { get; set; }
        public string PercentageSoughtType { get; set; }
        public string PlaceOfListing { get; set; }
        public bool? PostingDateIsSet { get; set; }
        public DateTime? PostingDateValue { get; set; }
        public string PostingDateType { get; set; }
        public string PostingDateUtcOffset { get; set; }
        public bool? PremiumFractionIsSet { get; set; }
        public string PremiumFractionPrimaryCurrencyCode { get; set; }
        public decimal? PremiumFractionPrimaryValue { get; set; }
        public string PremiumFractionSecondaryCurrencyCode { get; set; }
        public decimal? PremiumFractionSecondaryValue { get; set; }
        public string PremiumFractionType { get; set; }
        public string ProcessingStateCode { get; set; }
        public DateTime? PublicationWindowEndDate { get; set; }
        public string QuotationTypeCode { get; set; }
        public string RatingCode { get; set; }
        public bool? RecordDateIsSet { get; set; }
        public DateTime? RecordDateValue { get; set; }
        public string RecordDateType { get; set; }
        public string RecordDateUtcOffset { get; set; }
        public DateTime? ReferenceDate { get; set; }
        public bool? RefundOfNraIsSet { get; set; }
        public string RefundOfNraCurrencyCode { get; set; }
        public decimal? RefundOfNraValue { get; set; }
        public string RefundOfNraType { get; set; }
        public string RefundOfNraCode { get; set; }
        public decimal? RefundOfNraQuantity { get; set; }
        public string RefundOfNraQuantityTypeCode { get; set; }
        public bool? RefundOfNraIsCalculated { get; set; }
        public decimal? RefundOfNraValue2 { get; set; }
        public string RefundOfNraCurrency2Code { get; set; }
        public int? RelevantPropertiesHashcode { get; set; }
        public string RenounceableIndicatorCode { get; set; }
        public bool? ResultPublicationDateTimeIsSet { get; set; }
        public DateTime? ResultPublicationDateTimeValue { get; set; }
        public string ResultPublicationDateTimeType { get; set; }
        public string ResultPublicationDateTimeUtcOffset { get; set; }
        public decimal? SecurityPosition { get; set; }
        public int? SilverCopyCount { get; set; }
        public string State { get; set; }
        public string SwiftMessageFunctionCode { get; set; }
        public string TargetSystemId { get; set; }
        public string TargetSystemStateCode { get; set; }
        public string TaxAmountTypeCode { get; set; }
        public bool? TaxCreditRateIsSet { get; set; }
        public string TaxCreditRatePrimaryCurrencyCode { get; set; }
        public decimal? TaxCreditRatePrimaryValue { get; set; }
        public string TaxCreditRateSecondaryCurrencyCode { get; set; }
        public decimal? TaxCreditRateSecondaryValue { get; set; }
        public string TaxCreditRateType { get; set; }
        public bool? TaxOnIncomeIsSet { get; set; }
        public string TaxOnIncomePrimaryCurrencyCode { get; set; }
        public decimal? TaxOnIncomePrimaryValue { get; set; }
        public string TaxOnIncomeSecondaryCurrencyCode { get; set; }
        public decimal? TaxOnIncomeSecondaryValue { get; set; }
        public string TaxOnIncomeType { get; set; }
        public bool? TaxOnProfitsIsSet { get; set; }
        public string TaxOnProfitsPrimaryCurrencyCode { get; set; }
        public decimal? TaxOnProfitsPrimaryValue { get; set; }
        public string TaxOnProfitsSecondaryCurrencyCode { get; set; }
        public decimal? TaxOnProfitsSecondaryValue { get; set; }
        public string TaxOnProfitsType { get; set; }
        public bool? TaxRateIsSet { get; set; }
        public string TaxRatePrimaryCurrencyCode { get; set; }
        public decimal? TaxRatePrimaryValue { get; set; }
        public string TaxRateSecondaryCurrencyCode { get; set; }
        public decimal? TaxRateSecondaryValue { get; set; }
        public string TaxRateType { get; set; }
        public bool? TaxRelatedRateIsSet { get; set; }
        public string TaxRelatedRatePrimaryCurrencyCode { get; set; }
        public decimal? TaxRelatedRatePrimaryValue { get; set; }
        public string TaxRelatedRateSecondaryCurrencyCode { get; set; }
        public decimal? TaxRelatedRateSecondaryValue { get; set; }
        public string TaxRelatedRateType { get; set; }
        public bool? TidchIsSet { get; set; }
        public string TidchPrimaryCurrencyCode { get; set; }
        public decimal? TidchPrimaryValue { get; set; }
        public string TidchSecondaryCurrencyCode { get; set; }
        public decimal? TidchSecondaryValue { get; set; }
        public string TidchType { get; set; }
        public bool? TideuIsSet { get; set; }
        public string TideuPrimaryCurrencyCode { get; set; }
        public decimal? TideuPrimaryValue { get; set; }
        public string TideuSecondaryCurrencyCode { get; set; }
        public decimal? TideuSecondaryValue { get; set; }
        public string TideuType { get; set; }
        public string TransactionTypeCode { get; set; }
        public string TypeOfDividendCode { get; set; }
        public string TypeOfListingCode { get; set; }
        public string TypeOfPaymentAmountCode { get; set; }
        public string TypeOfPaymentAmountList { get; set; }
        public string ValidationTypeCode { get; set; }
        public string VdfAmortizationType { get; set; }
        public string VdfCashFlowId { get; set; }
        public string VdfCashflowType { get; set; }
        public string VdfChId { get; set; }
        public string VdfDividendSupplInfoCode { get; set; }
        public string VdfDividendTypeCode { get; set; }
        public string VdfMessageItemCode { get; set; }
        public string VdfPaymentAmountType { get; set; }
        public string WithholdingOfForeignTax { get; set; }
        public string WithholdingOfLocalTax { get; set; }
        public bool? WithholdingTaxRateIsSet { get; set; }
        public string WithholdingTaxRatePrimaryCurrencyCode { get; set; }
        public decimal? WithholdingTaxRatePrimaryValue { get; set; }
        public string WithholdingTaxRateSecondaryCurrencyCode { get; set; }
        public decimal? WithholdingTaxRateSecondaryValue { get; set; }
        public string WithholdingTaxRateType { get; set; }
        public string LinkedCustomProperties { get; set; }
        public string LinkedOptions { get; set; }
        public string LinkedSilverCopies { get; set; }
    }
}
