using System;
using System.Collections.Generic;

#nullable disable

namespace ODataDemo.Models
{
    public partial class Institution
    {
        public string Etag { get; set; }
        public long Id { get; set; }
        public bool? ActiveFlag { get; set; }
        public string Address { get; set; }
        public string AmficodeCode { get; set; }
        public string Attention { get; set; }
        public string BbgcompanyParentRelationshipCode { get; set; }
        public string BbgglobalCompanyId { get; set; }
        public string BbgglobalUltimateParentCompanyId { get; set; }
        public string BbgidglobalParentCompany { get; set; }
        public string BbgissuerNameType { get; set; }
        public string BbglegalFormCode { get; set; }
        public long? BbgparentId { get; set; }
        public long? BbgultimateParentId { get; set; }
        public string BicindustryGroupCode { get; set; }
        public string BicindustrySectorCode { get; set; }
        public string BicindustrySubgroupCode { get; set; }
        public string City { get; set; }
        public string CompanyDescription { get; set; }
        public string CompanyUrl { get; set; }
        public string CountryAddressCode { get; set; }
        public string CountryOfDomicileCode { get; set; }
        public string CountryOfIncorporationCode { get; set; }
        public string CountryOfRiskCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public bool? CustomerActiveIssues { get; set; }
        public string CustomerInstitutionNotes { get; set; }
        public string CustomerIssuerTypeCode { get; set; }
        public string CustomerRecordTypeCode { get; set; }
        public string Ekn { get; set; }
        public string ExchangeSymbol { get; set; }
        public string FactsetIndustryCodeCode { get; set; }
        public string Fax { get; set; }
        public string FiscalYearEnd { get; set; }
        public string FitchIssuerLongTermRatingCode { get; set; }
        public DateTime? FitchIssuerLongTermRatingDate { get; set; }
        public string GainId { get; set; }
        public string GicsGroupCode { get; set; }
        public string GicsIndustryCode { get; set; }
        public string GicsSectorCode { get; set; }
        public string GicsSubIndustryCode { get; set; }
        public string GkNumber { get; set; }
        public string IdBbcompany { get; set; }
        public string IdcorgId { get; set; }
        public long? ImmediateParentId { get; set; }
        public string IndustryGroupCode { get; set; }
        public string IndustrySectorCode { get; set; }
        public string IndustrySubgroupCode { get; set; }
        public string InstitutionRoleCode { get; set; }
        public DateTime? InstitutionUpdatedDate { get; set; }
        public string InternalInstitutionId { get; set; }
        public bool? IsLinkedtoInstrument { get; set; }
        public bool? IsUltimateParent { get; set; }
        public bool? IsUpdated { get; set; }
        public string IGainInstitutionId { get; set; }
        public long? IId { get; set; }
        public string JcrforeignCcyLongTermIssuerRatingCode { get; set; }
        public DateTime? JcrforeignCcyLongTermIssuerRatingDate { get; set; }
        public string JcrissuerLongTermRatingCode { get; set; }
        public DateTime? JcrissuerLongTermRatingDate { get; set; }
        public string JcrlocalCcyLongTermIssuerRatingCode { get; set; }
        public DateTime? JcrlocalCcyLongTermIssuerRatingDate { get; set; }
        public string LegalEntityCode { get; set; }
        public string LegalEntityTypeCode { get; set; }
        public string LegalFormCode { get; set; }
        public DateTime? LeiassignedDate { get; set; }
        public DateTime? LeidisabledDate { get; set; }
        public string LeientityStatusCode { get; set; }
        public string Leiid { get; set; }
        public DateTime? LeilastUpdate { get; set; }
        public string LeilegalForm { get; set; }
        public string LeiregistrationAddress { get; set; }
        public string LocalIssuerId { get; set; }
        public string LongName { get; set; }
        public string MarcissuerLongTermRatingCode { get; set; }
        public DateTime? MarcissuerLongTermRatingDate { get; set; }
        public string MoodyIssuerLongTermRatingCode { get; set; }
        public DateTime? MoodyIssuerLongTermRatingDate { get; set; }
        public string Name { get; set; }
        public long? OldUltimateParentId { get; set; }
        public string Phone { get; set; }
        public bool? PrevTwelveDthreeFlag { get; set; }
        public bool? PrevTwelveDthreeLockedFlag { get; set; }
        public string RambissuerLongTermRatingCode { get; set; }
        public DateTime? RambissuerLongTermRatingDate { get; set; }
        public string RedCode { get; set; }
        public string ReutersOrgId { get; set; }
        public string RidomesticCcyIssuerRatingCode { get; set; }
        public DateTime? RidomesticCcyIssuerRatingDate { get; set; }
        public string RifcissuerRatingCode { get; set; }
        public DateTime? RifcissuerRatingDate { get; set; }
        public string RiissuerRatingCode { get; set; }
        public DateTime? RiissuerRatingDate { get; set; }
        public string ShortName { get; set; }
        public string SpissuerLongTermRatingCode { get; set; }
        public DateTime? SpissuerLongTermRatingDate { get; set; }
        public string StateOfDomicileCode { get; set; }
        public string StateOfIncorporationCode { get; set; }
        public string StateProvinceAddress { get; set; }
        public DateTime? TotalSharesOutChangedate { get; set; }
        public decimal? TotalSharesOutstanding { get; set; }
        public DateTime? TotalSharesOutstandingDate { get; set; }
        public decimal? TotalSharesOutValue { get; set; }
        public DateTime? TwelveDthreeChangedDate { get; set; }
        public bool? TwelveDthreeFlag { get; set; }
        public string TwelveDthreeFlagChangedBy { get; set; }
        public bool? TwelveDthreeLockedFlag { get; set; }
        public DateTime? TwelveDthreeReviewedDate { get; set; }
        public DateTime? UltimateParentChangeDate { get; set; }
        public bool? UltimateParentLock { get; set; }
        public long? UltimateParentId { get; set; }
        public string LinkedBusinessClassifications { get; set; }
        public string LinkedCustomProperties { get; set; }
        public string LinkedNames { get; set; }
        public string LinkedRatings { get; set; }
        public string LinkedRelatedInstitutions { get; set; }
        public string LinkedSilverCopies { get; set; }
        public string LinkedSwifts { get; set; }
        public string LinkedTargetSystems { get; set; }
    }
}
