using System;
using System.Collections.Generic;

#nullable disable

namespace ODataDemo.Models
{
    public partial class Instrument
    {
        public string Etag { get; set; }
        public long Id { get; set; }
        public string AbsMbsassetTypeCode { get; set; }
        public int? AccruedDaysBetweenCpndates { get; set; }
        public int? AccruedInterest { get; set; }
        public bool? Active { get; set; }
        public int? AgeCalculated { get; set; }
        public string AlternativeBbticker { get; set; }
        public string AlternativeCommonCode { get; set; }
        public string AlternativeCusip { get; set; }
        public string AlternativeId1 { get; set; }
        public string AlternativeIsin { get; set; }
        public string AlternativeSedol { get; set; }
        public string AmficodeCode { get; set; }
        public decimal? AmountIssuedAccumulating { get; set; }
        public decimal? AmountIssuedOriginal { get; set; }
        public decimal? AmountOutstanding { get; set; }
        public DateTime? AmountOutstandingDate { get; set; }
        public decimal? AsOfCoupon { get; set; }
        public string AssetClass { get; set; }
        public string AssetTypeNew { get; set; }
        public long? AssimilatedAssetId { get; set; }
        public decimal? AttachmentPoint { get; set; }
        public decimal? BankruptPercentage { get; set; }
        public DateTime? BaseCpidate { get; set; }
        public decimal? BaseCpivalue { get; set; }
        public string BaseCurrencyCode { get; set; }
        public decimal? BasicSpread { get; set; }
        public int? BbgaccruedBasis { get; set; }
        public string BbgCompositeGlobalId { get; set; }
        public string BbgdataLicenseAssetClassCode { get; set; }
        public string BbgDayCountCode { get; set; }
        public string BbgglobalCompanyId { get; set; }
        public string BbgGlobalId { get; set; }
        public string BbglongTermFundObjectiveCode { get; set; }
        public string BbgpricingMethodCode { get; set; }
        public string BbgprimarySecurityYellowKeyCode { get; set; }
        public string BbgsecurityDescription { get; set; }
        public string BbgSecurityTypeCode { get; set; }
        public string BbgspecificCouponTypeCode { get; set; }
        public string BbgTicker { get; set; }
        public string BbgUniqueId { get; set; }
        public string BemaustraliaId { get; set; }
        public long? BenchmarkReferenceId { get; set; }
        public string BissettId { get; set; }
        public bool? BlackListed { get; set; }
        public string BloombergCode { get; set; }
        public string BloombergCodeInfo { get; set; }
        public bool? BloombergData { get; set; }
        public decimal? BloombergFactor { get; set; }
        public string BloombergGlobalId { get; set; }
        public string BloombergYellowKeyOverride { get; set; }
        public string BnyMellonId { get; set; }
        public string BondSeries { get; set; }
        public string BovespaTicker { get; set; }
        public string CalendarDayOfCouponPaymentCode { get; set; }
        public string CallablePutableCode { get; set; }
        public DateTime? CallDate { get; set; }
        public string CallFeatureCode { get; set; }
        public string CallFrequencyCode { get; set; }
        public decimal? CallPrice { get; set; }
        public string CapitalProtectionCode { get; set; }
        public string CapitalTriggerTypeCode { get; set; }
        public DateTime? CashDividendConfirmationDate { get; set; }
        public bool? Catastrophe { get; set; }
        public string CategoryCode { get; set; }
        public string CertificateUnderlyingTypeCode { get; set; }
        public string CertificationType { get; set; }
        public string Cficode { get; set; }
        public string CharlesRiverId { get; set; }
        public string CiccategoryCode { get; set; }
        public string Ciccode { get; set; }
        public string Cinsid { get; set; }
        public DateTime? CloseDate { get; set; }
        public string Cmbstype { get; set; }
        public string Cmoclass { get; set; }
        public string Cmoseries { get; set; }
        public string CollateralCountryCode { get; set; }
        public string CollateralDescriptionCode { get; set; }
        public string CollateralPortfolioCode { get; set; }
        public string CollateralTypeCode { get; set; }
        public decimal? CollateralValue { get; set; }
        public string CommonCode { get; set; }
        public string CompletenessLevelCode { get; set; }
        public decimal? ContractSize { get; set; }
        public decimal? ConversionFixedExchangeRate { get; set; }
        public decimal? ConversionPrice { get; set; }
        public decimal? ConversionRatio { get; set; }
        public DateTime? ConversionStartDate { get; set; }
        public string ConversionTypeCode { get; set; }
        public DateTime? ConversionUntilDate { get; set; }
        public DateTime? ConvertibleExpirationDate { get; set; }
        public string CountryOfDomicileCode { get; set; }
        public string CountryOfGuarantorCode { get; set; }
        public string CountryOfIssueCode { get; set; }
        public string CountryOfListingCode { get; set; }
        public string CountryOfRiskCode { get; set; }
        public DateTime? CouponAsOfDate { get; set; }
        public string CouponCurrencyCode { get; set; }
        public string CouponFrequencyCode { get; set; }
        public decimal? CouponRate { get; set; }
        public string CouponTypeCode { get; set; }
        public DateTime? CouponTypeResetDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public string CreditEnhancementTypeCode { get; set; }
        public DateTime? CurrentCouponPaymentExDividendDate { get; set; }
        public decimal? CurrentNet { get; set; }
        public decimal? CurrentWac { get; set; }
        public decimal? CurrentWam { get; set; }
        public string Cusip { get; set; }
        public string DayCountCode { get; set; }
        public string DefaultCurrency { get; set; }
        public DateTime? DefaultDate { get; set; }
        public decimal? Delta { get; set; }
        public decimal? DetachmentPoint { get; set; }
        public string DividendFrequencyCode { get; set; }
        public decimal? DividendIndicated1YearGross { get; set; }
        public string DvdshareTemp { get; set; }
        public string EarlyRedemptionInfo { get; set; }
        public string EquityFundamentalCurrencyCode { get; set; }
        public string Eqydvdtemp { get; set; }
        public string ExchangeCode { get; set; }
        public int? ExDividendDays { get; set; }
        public DateTime? ExerciseEndDate { get; set; }
        public string ExerciseTypeCode { get; set; }
        public DateTime? ExpectedMaturityDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public DateTime? ExpiryDate144A { get; set; }
        public decimal? Factor { get; set; }
        public DateTime? FactorEffectiveDate { get; set; }
        public string FactsetIndustryCode { get; set; }
        public bool? FederallyTaxable { get; set; }
        public DateTime? FeedLastUpdateDate { get; set; }
        public DateTime? FeedStartRestrictedStatus { get; set; }
        public DateTime? FirstCouponPaymentDate { get; set; }
        public DateTime? FirstExDividendDate { get; set; }
        public DateTime? FirstInterestAccrualDate { get; set; }
        public DateTime? FirstPrincipalPayDate { get; set; }
        public DateTime? FirstSettleDate { get; set; }
        public DateTime? FirstTradeDate { get; set; }
        public string Fisn { get; set; }
        public decimal? FixedCpnvalue { get; set; }
        public string FixedToFloatCouponFrequencyCode { get; set; }
        public string FixedToFloatDayCountCode { get; set; }
        public decimal? FloaterBenchmarkMultiplier { get; set; }
        public string FloaterFormula { get; set; }
        public string FloaterIndex { get; set; }
        public decimal? FloaterSpread { get; set; }
        public string FundAssetClassFocusCode { get; set; }
        public string FundCompanyName { get; set; }
        public string FundGeographicalFocusCode { get; set; }
        public string FundIndustryFocusCode { get; set; }
        public string FundInitialCurrencyCode { get; set; }
        public decimal? FundInvestedInCashAndOthers { get; set; }
        public decimal? FundInvestedInCorpSecurities { get; set; }
        public decimal? FundInvestedInEquitySecurities { get; set; }
        public decimal? FundinvestedinGovernmentSecurities { get; set; }
        public decimal? FundInvestedInMtgeSecurities { get; set; }
        public decimal? FundInvestedInMuniSecurities { get; set; }
        public decimal? FundinvestedinPrefSecurities { get; set; }
        public string FundManagementCompany { get; set; }
        public string FundManagementStyleCode { get; set; }
        public string FundMarketCapFocusCode { get; set; }
        public string FundMaturityFocusCode { get; set; }
        public string FundNavcurrencyCode { get; set; }
        public decimal? FundNavvalue { get; set; }
        public string FundPricingFrequencyCode { get; set; }
        public string FundPricingSource { get; set; }
        public string FundRatingClassFocusCode { get; set; }
        public DateTime? FundRedepmtionDate { get; set; }
        public string FundStrategyCode { get; set; }
        public string FundTaxStatus { get; set; }
        public decimal? FundTotalAssets { get; set; }
        public string FundTotalAssetsCurrencyCode { get; set; }
        public string FundTypeCode { get; set; }
        public string FuturesAndOptionsCategoryCode { get; set; }
        public DateTime? FuturesFirstDeliveryDate { get; set; }
        public DateTime? FuturesFirstNoticeDate { get; set; }
        public decimal? FuturesInitialMarginSpeculator { get; set; }
        public DateTime? FuturesLastDeliveryDate { get; set; }
        public DateTime? FuturesRollDate { get; set; }
        public string GainId { get; set; }
        public int? GainIssuerId { get; set; }
        public string GeographicalZoneCode { get; set; }
        public string GicssubIndustryCode { get; set; }
        public string GlobalAssetClassCode { get; set; }
        public string GlobalAssetTypeCode { get; set; }
        public bool? Gplusflag { get; set; }
        public string Gplusid { get; set; }
        public decimal? GrossDividend1YearGrowthRate { get; set; }
        public decimal? GrossDividend3YearGrowthRate { get; set; }
        public string Guarantor { get; set; }
        public bool? Has144AregSrights { get; set; }
        public bool? HasAlternativeMinimumTax { get; set; }
        public bool? HasContingentDebt { get; set; }
        public bool? HasEndAccDateAtMonthEnd { get; set; }
        public bool? HasInterestCapitalization { get; set; }
        public bool? HasInterestPayDateAtMonthEnd { get; set; }
        public string HasLocspacode { get; set; }
        public bool? HasLong1stCoupon { get; set; }
        public bool? HasMakeWholeCallPossible { get; set; }
        public bool? HasMortgageIsPaidOff { get; set; }
        public bool? HasProspective { get; set; }
        public bool? HasSharesIncluded { get; set; }
        public bool? HasShort1stCoupon { get; set; }
        public bool? HasSolvencyIi { get; set; }
        public int? IndexLag { get; set; }
        public string IndexLagUnitCode { get; set; }
        public string IndexName { get; set; }
        public string IndexTypeCode { get; set; }
        public long? IndexId { get; set; }
        public string InflationIndexPriceFreq { get; set; }
        public DateTime? InitialPublicOfferDate { get; set; }
        public decimal? InitialPubOfferSharePrice { get; set; }
        public string InstrumentGroupCode { get; set; }
        public string InstrumentTypeCode { get; set; }
        public decimal? InsurerPercentage { get; set; }
        public string InterestBusinessDayConventionCode { get; set; }
        public string InterestCalculationTypeCode { get; set; }
        public string InterestPaymentMethodCode { get; set; }
        public decimal? InterestShortFall { get; set; }
        public decimal? Ipoprice { get; set; }
        public bool? Is144A { get; set; }
        public bool? IsAccumulatingFund { get; set; }
        public bool? IsAgencyBacked { get; set; }
        public bool? IsAuctionRate { get; set; }
        public bool? IsBearerSecurity { get; set; }
        public bool? IsCallable { get; set; }
        public bool? IsCalled { get; set; }
        public bool? IsClosedEndFund { get; set; }
        public bool? IsContingentConvertible { get; set; }
        public bool? IsConvertible { get; set; }
        public bool? IsCouponInDefault { get; set; }
        public bool? IsCovered { get; set; }
        public bool? IsCreditLinked { get; set; }
        public bool? IscurrentGovernmentBond { get; set; }
        public bool? IsDefaulted { get; set; }
        public bool? IsDeflationProtected { get; set; }
        public bool? IsDualCurrency { get; set; }
        public bool? IsErisa { get; set; }
        public bool? IsExchangeable { get; set; }
        public bool? IsFixtoFloat { get; set; }
        public bool? IsFloater { get; set; }
        public bool? IsFloattoFix { get; set; }
        public bool? IsFundOfFunds { get; set; }
        public bool? IsHybridBond { get; set; }
        public bool? IsHybridCumulative { get; set; }
        public bool? IsHybridDeferredPaymentAllowed { get; set; }
        public string Isin { get; set; }
        public bool? IsIndexInterpolated { get; set; }
        public bool? IsInflationLinked { get; set; }
        public bool? IsIrregularCashFlow { get; set; }
        public bool? IsIslamic { get; set; }
        public string IslamicBondTypeCode { get; set; }
        public string IsMandatoryConversion { get; set; }
        public bool? IsPartiallyCalled { get; set; }
        public bool? IsPerpetual { get; set; }
        public bool? IsPrepaymentStructuredProduct { get; set; }
        public bool? IsPrivatePlacement { get; set; }
        public bool? IsPutable { get; set; }
        public bool? IsRedeeming { get; set; }
        public bool? IsRegisteredSecurity { get; set; }
        public bool? IsRegS { get; set; }
        public bool? IsRemarketed { get; set; }
        public bool? IsReverseConvertible { get; set; }
        public bool? IsSecured { get; set; }
        public bool? IsSenior { get; set; }
        public bool? IsSinkable { get; set; }
        public bool? IsStandard { get; set; }
        public bool? IsStructuredNote { get; set; }
        public bool? IsSubordinated { get; set; }
        public string IssueCurrencyCode { get; set; }
        public DateTime? IssueDate { get; set; }
        public string IssueDescription13F { get; set; }
        public decimal? IssuePrice { get; set; }
        public string IssuerDescription13F { get; set; }
        public long? IssuerId { get; set; }
        public bool? IsSyntheticConvertible { get; set; }
        public bool? IsSyntheticLoan { get; set; }
        public bool? IsTaxableBond { get; set; }
        public bool? IsUnitTraded { get; set; }
        public bool? IsUnsecured { get; set; }
        public bool? IsUpdated { get; set; }
        public bool? IsUssection13F { get; set; }
        public bool? IsVariable { get; set; }
        public string IGainInstrumentId { get; set; }
        public long? IId { get; set; }
        public DateTime? LastCallableDate { get; set; }
        public DateTime? LastClosePriceDate { get; set; }
        public DateTime? LastCouponDate { get; set; }
        public decimal? LastPrice { get; set; }
        public DateTime? LastRefixDate { get; set; }
        public DateTime? LastTradeDate { get; set; }
        public decimal? LatestSinkingFundFactor { get; set; }
        public DateTime? LegalFinalMaturity { get; set; }
        public string LoanFacilityName { get; set; }
        public string LocalExchangeSymbol { get; set; }
        public DateTime? LocexpirationDate { get; set; }
        public decimal? Locspapercentage { get; set; }
        public string LongName { get; set; }
        public decimal? MarketCapitalization { get; set; }
        public string MarketStatusCode { get; set; }
        public string MarketTicker { get; set; }
        public string MarkitLxid { get; set; }
        public DateTime? MaturityDate { get; set; }
        public string MaturityTypeCode { get; set; }
        public string MbsprodCodeCode { get; set; }
        public decimal? MinimumIncrement { get; set; }
        public decimal? MinimumPurchaseAmount { get; set; }
        public decimal? MinumumTradableAmount { get; set; }
        public DateTime? ModifiedDurationInternal { get; set; }
        public string MortgageCollateralTypeCode { get; set; }
        public string MortgageDealTypeCode { get; set; }
        public decimal? MortgageLoanAge { get; set; }
        public string MortgageTrancheTypeCode { get; set; }
        public DateTime? MostRecentAccrRtStartDate { get; set; }
        public DateTime? MostRecentDefaultDate { get; set; }
        public DateTime? MtgeFirstProjectedCashflowDate { get; set; }
        public DateTime? MtgeNextPayDatePerSettle { get; set; }
        public bool? MultipleShares { get; set; }
        public string MunicipalIndustryTypeCode { get; set; }
        public string MunicipalIssueName { get; set; }
        public string MunicipalIssueTypeCode { get; set; }
        public string MunicipalScccode { get; set; }
        public string MunicipalTaxStatusCode { get; set; }
        public string MuniSscClassCodeCode { get; set; }
        public string NaceclassCode { get; set; }
        public string Nacecode { get; set; }
        public string NacedivisionCode { get; set; }
        public string NacegroupCode { get; set; }
        public string NacesectorCode { get; set; }
        public string NameOfProject { get; set; }
        public bool? NegativeInterest { get; set; }
        public decimal? NetDividend1YearGrowthRate { get; set; }
        public decimal? NetDividend3YearGrowthRate { get; set; }
        public DateTime? NextCouponPayDate { get; set; }
        public DateTime? NextFactorDate { get; set; }
        public DateTime? NextRefixDate { get; set; }
        public decimal? NextSinkAmount { get; set; }
        public DateTime? NextSinkingDate { get; set; }
        public decimal? NextSinkingPrice { get; set; }
        public int? NominalPaymentDay { get; set; }
        public int? NumberOfPositions { get; set; }
        public int? NumOfDeferredPaymentsAllowed { get; set; }
        public string Occ21symbol { get; set; }
        public DateTime? OpenDate { get; set; }
        public string OptionExoticTypeCode { get; set; }
        public string OptionTypeCode { get; set; }
        public decimal? OriginalNet { get; set; }
        public decimal? OriginalWac { get; set; }
        public decimal? OriginalWam { get; set; }
        public decimal? ParValue { get; set; }
        public string ParValueCurrencyCode { get; set; }
        public int? PayDelay { get; set; }
        public string PaymentRankCode { get; set; }
        public DateTime? PenultimateCpndate { get; set; }
        public decimal? PercentOfIssue { get; set; }
        public string PerformanceSectorCode { get; set; }
        public string PoolNumber { get; set; }
        public string PoolTypeCode { get; set; }
        public decimal? PositionsAmount { get; set; }
        public decimal? PrepaymentSpeed { get; set; }
        public string PrepaymentSpeedSource { get; set; }
        public string PreRefundedEtmcallStatusCode { get; set; }
        public DateTime? PreRefundedEtmdate { get; set; }
        public decimal? PreRefundedEtmprice { get; set; }
        public DateTime? PreviousCouponDate { get; set; }
        public DateTime? PreviousPrincipalPaymentDate { get; set; }
        public string PriceProviderCode { get; set; }
        public string PriceUnitCode { get; set; }
        public string PricingFrequencyCode { get; set; }
        public string PricingInstrumentCode { get; set; }
        public string PrimarySecurityCurrencyCode { get; set; }
        public decimal? PrincipalLosses { get; set; }
        public int? PrincipalPayDelay { get; set; }
        public string ProductTypeCode { get; set; }
        public string ProjectId { get; set; }
        public string ProjectNameCode { get; set; }
        public string PutFeatureCode { get; set; }
        public string PutFrequencyCode { get; set; }
        public string QuotationMode { get; set; }
        public string QuotationTypeCode { get; set; }
        public string RedCode { get; set; }
        public string RedemptionCurrencyCode { get; set; }
        public int? RedemptionFrequency { get; set; }
        public decimal? RedemptionValue { get; set; }
        public string ReferenceCpiindex { get; set; }
        public long? ReferenceIndexId { get; set; }
        public string ReferencePeriodCode { get; set; }
        public string RegionCode { get; set; }
        public string RelativeIndex { get; set; }
        public DateTime? RemarketDate { get; set; }
        public string ResetFrequencyCode { get; set; }
        public string ReutersAssetId { get; set; }
        public decimal? ReutersFactor { get; set; }
        public string ReutersLinnumber { get; set; }
        public string ReutersQuoteId { get; set; }
        public string ReutersRic { get; set; }
        public decimal? RoundLot { get; set; }
        public string SecrestrictionsCode { get; set; }
        public bool? Security12D3flag { get; set; }
        public decimal? SecurityActivationPrice { get; set; }
        public DateTime? SecurityActivationPriceDate { get; set; }
        public string SecurityCountryOfIncorporationCode { get; set; }
        public string SecurityDescription { get; set; }
        public string SecurityLegalName1 { get; set; }
        public string SecurityLegalName2 { get; set; }
        public string SecurityLegalName3 { get; set; }
        public string SecurityLegalName4 { get; set; }
        public string SecurityLegalName5 { get; set; }
        public string SecurityLegalName6 { get; set; }
        public string Sedol { get; set; }
        public string Sedol2 { get; set; }
        public string Series { get; set; }
        public string SettlementCalendarCode { get; set; }
        public string SettlementCurrencyCode { get; set; }
        public string SettlementTypeCode { get; set; }
        public decimal? SharesOutstanding { get; set; }
        public DateTime? SharesOutstandingDate { get; set; }
        public string ShortName { get; set; }
        public string ShortTermMuniType { get; set; }
        public string SinkingFrequencyCode { get; set; }
        public string SinkScheduleAmountType { get; set; }
        public string SinkTypeCode { get; set; }
        public string SixCode { get; set; }
        public string SolvencyIicollateralTypeCode { get; set; }
        public string SourceId { get; set; }
        public string SponsorId { get; set; }
        public string SponsorshipTypeCode { get; set; }
        public string Status { get; set; }
        public string StockExchangeNumber { get; set; }
        public string StockExchangeSecurityCode { get; set; }
        public decimal? StrikePrice { get; set; }
        public decimal? StrikeRate { get; set; }
        public string StripTypeCode { get; set; }
        public string SubAssetGroupCode { get; set; }
        public string SuspectHandlingField1 { get; set; }
        public string SuspectHandlingField2 { get; set; }
        public string SuspectHandlingField3 { get; set; }
        public string SuspectHandlingField4 { get; set; }
        public string SuspectHandlingField5 { get; set; }
        public string SwapDescription { get; set; }
        public int? SwapVersion { get; set; }
        public string SyntheticStructuredProductCode { get; set; }
        public string TaxCountryCode { get; set; }
        public decimal? TelekursFactor { get; set; }
        public string Ticker { get; set; }
        public decimal? TickSize { get; set; }
        public decimal? TickValue { get; set; }
        public decimal? TotalSharesOutstandingAllClasses { get; set; }
        public string TradeCurrencyCode { get; set; }
        public int? TradeLotSize { get; set; }
        public string TradePlaceCode { get; set; }
        public bool? TradingStatus { get; set; }
        public string TrancheClassificationIdcode { get; set; }
        public string TranchePoolTypeCode { get; set; }
        public string TypeOfBondCode { get; set; }
        public string TypeofDebtSecurityCode { get; set; }
        public string UltimateBorrower { get; set; }
        public DateTime? UnadjustedFirstCoupon { get; set; }
        public string UnderlyingDescription { get; set; }
        public string UnderlyingGaininstrumentId { get; set; }
        public decimal? UnderlyingUnitsForInterestPayment { get; set; }
        public long? UnderlyingId { get; set; }
        public long? UnderwriterId { get; set; }
        public bool? UnitPriceFlag { get; set; }
        public string UsStateCode { get; set; }
        public string ValorNumber { get; set; }
        public DateTime? ValueDate { get; set; }
        public string Valueof1Pt { get; set; }
        public decimal? VariableAnnualReturn { get; set; }
        public string VendorInstrumentName { get; set; }
        public string VendorIssuerName { get; set; }
        public decimal? VotingRights { get; set; }
        public string VotingRightsStatusCode { get; set; }
        public string WallStreetOfficeId { get; set; }
        public string Wkn { get; set; }
        public string Wrtcovered { get; set; }
        public string YellowKeyCode { get; set; }
        public decimal? YieldToMaturity { get; set; }
        public long? MifidId { get; set; }
        public string LinkedBondOptionalities { get; set; }
        public string LinkedBusinessClassifications { get; set; }
        public string LinkedCouponSchedules { get; set; }
        public string LinkedCustomComponents1 { get; set; }
        public string LinkedCustomComponents2 { get; set; }
        public string LinkedCustomComponents3 { get; set; }
        public string LinkedCustomComponents4 { get; set; }
        public string LinkedCustomComponents5 { get; set; }
        public string LinkedCustomProperties { get; set; }
        public string LinkedDividendProjectionSchedules { get; set; }
        public string LinkedDividendSchedules { get; set; }
        public string LinkedFactorProjectionsSchedule { get; set; }
        public string LinkedFactorSchedules { get; set; }
        public string LinkedFeesCharges { get; set; }
        public string LinkedInflationsLinked { get; set; }
        public string LinkedLegs { get; set; }
        public string LinkedListings { get; set; }
        public string LinkedMifid { get; set; }
        public string LinkedNames { get; set; }
        public string LinkedPrepaymentSpeeds { get; set; }
        public string LinkedRatings { get; set; }
        public string LinkedRelatedInstitutions { get; set; }
        public string LinkedRelatedInstruments { get; set; }
        public string LinkedSilverCopies { get; set; }
        public string LinkedSinkingSchedules { get; set; }
    }
}
